CREATE TABLE ACCOUNTS(
    ID int(5) NOT NULL AUTO_INCREMENT,
    NOME char(20)
    EMAIL char(100),
    SENHA char(500),
    PREMIUN_ACCOUNT int(3),
    PREMIUN_ACCOUNT_ENDS int(10),
    CREATION char(11)
)

CREATE TABLE PLAYERS(
    PLAYER_ID varchar(5) NOT NULL AUTO_INCREMENT,
    PLAYER_NAME varchar(2),
    PLAYER_VOCATION varchar(2),
    PLAYER_LEVEL int(4),
    PLAYER_HEALT int(6),
    PLAYER_HEALTMAX int(6),
    PLAYER_MANA int(6),
    PLAYER_MANAMAX int(6),
    PLAYER_EXPERIENCE int(30),
    PLAYER_CAP int(5),
    PLAYER_MAGIC int(4),
    PLAYER_AXE  int(4),
    PLAYER_CLUB int(4),
    PLAYER_SWORD int(4),
    PLAYER_DISTANCE int(4),
    PLAYER_SHIELDING int(4),
    PLAYER_FISHING int(4),
    SEX varchar(6),
    STAMINA int(50)
)

CREATE TABLE PLAYER_ITEMS(

)

CREATE TABLE PLAYER_ITEMS_BOX(

)

CREATE TABLE PLAYER_SPELLS(
    
)

CREATE TABLE PLAYER_KILLS(

)

CREATE TABLE DEAD_PLAYERS(

)

CREATE TABLE ITENS_SHOP(

)

CREATE TABLE SHOP_HISTORY(

)

CREATE TABLE SHOP_BUY(

)

CREATE TABLE TIBIA_COINS(

)

CREATE TABLE MARKET_HISTORY(

)

CREATE TABLE MARKET_ITEMS(

)

CREATE TABLE MARKET_OFFERS(

)